### ISSUE TITLE
Push the wiki to the main repo with a bot

### ISSUE THREAD

**Issue by liach** [kashike/migration#1]
Every time the wiki changes, as a bot receives a notification from a webhook, it should be able to clone the repo from `https://github.com/kashike/migration.wiki.git` and push all branches to `https://github.com/kashike/migration`. This would help visualizing the wiki in the file form.

**Comment by kashike** [comment]
The wiki isn't used anymore.
https://github.com/ModCoderPack/MCPBot-Issues/tree/master/migrations
